### PR TITLE
todo-list ui

### PR DESCRIPTION
**Pull request by mwinel**
**What does this PR do?**
This PR adds a user ` signup ` page, ` login ` page, ` index ` page and ` user_profile ` page. This PR is just a simulation of the complete todo app.

**What works:**
- Add a new todo item
- Mark todo items as done
- Delete todo items
- Navigate to all the required pages
- View user profile

**How to test this:**
[Check out the project user interface](https://mwinel.github.io/todo-list/ui/index.html)
The UI has the following necessary pages as specified below.
- [user signup](https://mwinel.github.io/todo-list/ui/signup.html), enables user to create an account.
- [user login](https://mwinel.github.io/todo-list/ui/login.html), enables user to login into the app.
- [index page](https://mwinel.github.io/todo-list/ui/index.html), enables user to view and add their todo items.
- [user profile](https://mwinel.github.io/todo-list/ui/user_profile.html), enables a user to view their profile.

@nuwagalb, @codjoero, @lubwamabenja, @Ginnynjau, @archbishop12 help me review this...

### CODE REVIEW

**Comment by lubwamabenja** [comment]
Your website looks simple 
i think you can go ahead and merge

**Comment by habatkasa** [comment]
this is good bro... merge it

**Comment by habatkasa** [comment]
just wondering how to make strike through on my list also...
did you create a different page with the same list but striked through and made it a link to every list item on the main list?

**Comment by mwinel** [comment]
@habatkasa I am guessing you are asking about the ` user_profile ` page. I just created a different page which just simulates a todo-list.

**Pull request merged**
